version : '3'

services :

  cassandra :
    container_name : cassandra
    image : cassandra
    restart : always
    ports:
      - 9042:9042

  config :
    image : hyness/spring-cloud-config-server
    restart : always
    container_name : config
    environment : 
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/samoylenko-bogdan/config-server.git
    ports:
      - 8888:8888